# Generated by Django 4.1.3 on 2022-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsstory_favourited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/600', max_length=1000),
        ),
    ]
